export const styleFields = [
    {
        key: 'dimensions',
        label: 'Size',
        type: 'dimensions',
        keys: ['width', 'height'],
        group: 'Advanced',
    },
    {key: 'fullWidth', label: 'Stretch to full screen width', type: 'boolean', group: 'Advanced'},
    {key: 'margin', label: 'Outer margins', type: 'spacing', group: 'Advanced'},
    {key: 'padding', label: 'Inner padding', type: 'spacing', group: 'Advanced'},
    {key: 'backgroundColor', label: 'Background color', type: 'color', group: 'Advanced'},
    {key: 'backgroundImage', label: 'Background image', type: 'image', group: 'Advanced'},
    {
        key: 'backgroundSize',
        label: 'Background fit',
        type: 'segmented',
        options: [
            {value: 'cover', label: '', icon: 'FitCover', title: 'Cover — fill the block, crop the overflow'},
            {value: 'contain', label: '', icon: 'FitContain', title: 'Contain — fit inside, keep the ratio'},
        ],
        group: 'Advanced',
    },
    {
        key: 'backgroundPosition',
        label: 'Background position',
        type: 'segmented',
        cols: 3,
        options: [
            {value: 'left top', label: '↖', title: 'Top-left'},
            {value: 'center top', label: '↑', title: 'Top'},
            {value: 'right top', label: '↗', title: 'Top-right'},
            {value: 'left center', label: '←', title: 'Left'},
            {value: 'center center', label: '●', title: 'Center'},
            {value: 'right center', label: '→', title: 'Right'},
            {value: 'left bottom', label: '↙', title: 'Bottom-left'},
            {value: 'center bottom', label: '↓', title: 'Bottom'},
            {value: 'right bottom', label: '↘', title: 'Bottom-right'},
        ],
        group: 'Advanced',
    },
    // Light text on a photograph is only readable with something between the
    // two, and the something has to sit under the block's own children.
    {key: 'backgroundOverlay', label: 'Darken background', type: 'slider', min: 0, max: 1, step: 0.05, group: 'Advanced'},
    {key: 'link', label: 'Link', type: 'text', placeholder: '/women.html', group: 'Advanced'},
    {key: 'color', label: 'Text color', type: 'color', group: 'Advanced'},
    {
        key: 'fontFamily',
        label: 'Font',
        type: 'fontFamily',
        inlineNumber: {key: 'fontSize', placeholder: '14', suffix: 'px', width: 64},
        group: 'Advanced',
    },
    {
        key: 'textAlign',
        label: 'Text alignment',
        type: 'segmented',
        options: [
            {value: 'left', label: '', icon: 'AlignLeft', title: 'Left'},
            {value: 'center', label: '', icon: 'AlignCenter', title: 'Center'},
            {value: 'right', label: '', icon: 'AlignRight', title: 'Right'},
        ],
        group: 'Advanced',
    },
    {key: 'borderRadius', label: 'Corner radius', type: 'cornerRadius', group: 'Advanced'},
    {
        key: 'borderSides',
        label: 'Border',
        type: 'segmented',
        options: [
            {value: 'all', label: '', icon: 'BorderAll', title: 'All sides'},
            {value: 'top', label: '', icon: 'BorderTop', title: 'Top'},
            {value: 'bottom', label: '', icon: 'BorderBottom', title: 'Bottom'},
            {value: 'left', label: '', icon: 'BorderLeft', title: 'Left'},
            {value: 'right', label: '', icon: 'BorderRight', title: 'Right'},
        ],
        group: 'Advanced',
    },
    {
        key: 'borderStyle',
        label: 'Line',
        type: 'segmented',
        options: [
            {value: 'none', label: '', icon: 'LineNone', title: 'No border'},
            {value: 'solid', label: '', icon: 'LineSolid', title: 'Solid'},
            {value: 'dashed', label: '', icon: 'LineDashed', title: 'Dashed'},
            {value: 'dotted', label: '', icon: 'LineDotted', title: 'Dotted'},
            {value: 'double', label: '', icon: 'LineDouble', title: 'Double'},
        ],
        inlineNumber: {key: 'borderWidth', placeholder: '1', suffix: 'px', width: 56},
        group: 'Advanced',
    },
    {key: 'borderWidth', label: 'Line thickness (px)', type: 'number', placeholder: '1', group: 'Advanced'},
    {key: 'borderColor', label: 'Line color', type: 'color', group: 'Advanced'},
];
