export default {
    label: 'Button',
    category: 'content',
    icon: '▢',
    acceptsChildren: false,
    // Has an href of its own; a second anchor around it would nest.
    hideStyleFields: ['link'],
    allowedIn: ['page', 'Grid', 'Box'],
    defaultProps: {
      text: 'Button',
      href: '#',
      backgroundColor: '#2563eb',
      color: '#ffffff',
      fontSize: 14,
      padding: '12px 24px',
      borderWidth: 0,
      borderColor: '#2563eb',
      borderStyle: 'solid',
      fullWidth: false,
      textAlign: 'center',
    },
    propsSchema: {
      href: { label: 'Link', type: 'text', placeholder: '/cart', group: 'Button' },
      fullWidth: { label: 'Stretch to full container width', type: 'boolean', group: 'Button' },
      fontFamily: {
        label: 'Font',
        type: 'fontFamily',
        inlineNumber: { key: 'fontSize', placeholder: '14', suffix: 'px', width: 64 },
        group: 'Button',
      },
      fontSize: { label: 'Font size', type: 'number', placeholder: '14', group: 'Button' },
      color: { label: 'Text color', type: 'color', group: 'Button' },
      backgroundColor: { label: 'Background color', type: 'color', group: 'Button' },
      padding: { label: 'Inner padding', type: 'spacing', group: 'Advanced' },
      borderColor: { label: 'Border color', type: 'color', group: 'Button' },
      textAlign: {
        label: 'Text alignment',
        type: 'segmented',
        options: [
          { value: 'left', label: '', icon: 'AlignLeft', title: 'Left' },
          { value: 'center', label: '', icon: 'AlignCenter', title: 'Center' },
          { value: 'right', label: '', icon: 'AlignRight', title: 'Right' },
        ],
        group: 'Button',
      },
      textTransform: {
        label: 'Case',
        type: 'segmented',
        options: [
          { value: 'none', label: '', icon: 'CaseMixed', title: 'As typed' },
          { value: 'uppercase', label: '', icon: 'CaseUpper', title: 'UPPERCASE' },
          { value: 'lowercase', label: '', icon: 'CaseLower', title: 'lowercase' },
          { value: 'capitalize', label: '', icon: 'CaseCap', title: 'Capitalize Words' },
        ],
        group: 'Button',
      },
      // Secondary typography & border-stroke controls live in Advanced for
      // Button — kept out of the primary "Button" group to reduce noise.
      fontWeight: { label: 'Weight', type: 'fontWeight', group: 'Advanced' },
      fontStyle: {
        label: 'Style',
        type: 'segmented',
        options: [
          { value: 'normal', label: '', icon: 'StyleNormal', title: 'Regular' },
          { value: 'italic', label: '', icon: 'StyleItalic', title: 'Italic' },
        ],
        group: 'Advanced',
      },
      textDecoration: {
        label: 'Decoration',
        type: 'segmented',
        options: [
          { value: 'none', label: '', icon: 'DecorNone', title: 'None' },
          { value: 'underline', label: '', icon: 'DecorUnderline', title: 'Underline' },
          { value: 'line-through', label: '', icon: 'DecorLineThrough', title: 'Strikethrough' },
          { value: 'overline', label: '', icon: 'DecorOverline', title: 'Overline' },
        ],
        group: 'Advanced',
      },
      letterSpacing: { label: 'Letter spacing', type: 'letterSpacing', group: 'Advanced' },
      borderStyle: {
        label: 'Line',
        type: 'segmented',
        options: [
          { value: 'none', label: '', icon: 'LineNone', title: 'No border' },
          { value: 'solid', label: '', icon: 'LineSolid', title: 'Solid' },
          { value: 'dashed', label: '', icon: 'LineDashed', title: 'Dashed' },
          { value: 'dotted', label: '', icon: 'LineDotted', title: 'Dotted' },
          { value: 'double', label: '', icon: 'LineDouble', title: 'Double' },
        ],
        inlineNumber: { key: 'borderWidth', placeholder: '1', suffix: 'px', width: 56 },
        group: 'Advanced',
      },
      borderWidth: { label: 'Border width (px)', type: 'number', placeholder: '0', group: 'Advanced' },
    },
};
