export default {
    label: 'Heading',
    category: 'content',
    icon: 'H',
    acceptsChildren: false,
    allowedIn: ['page', 'Grid'],
    defaultProps: {
      text: 'Heading',
      href: '',
      level: 2,
      color: '',
      textAlign: 'left',
      fontWeight: 'bold',
      fontStyle: 'normal',
      textDecoration: 'none',
      textTransform: 'none',
      fontFamily: 'inherit',
      letterSpacing: 'normal',
      fontSize: '',
    },
    propsSchema: {
      level: {
        label: 'Level',
        type: 'segmented',
        options: [
          { value: 1, label: 'H1', title: 'Heading 1' },
          { value: 2, label: 'H2', title: 'Heading 2' },
          { value: 3, label: 'H3', title: 'Heading 3' },
          { value: 4, label: 'H4', title: 'Heading 4' },
        ],
        resetOnChange: ['fontSize'],
        group: 'Heading',
      },
      href: { label: 'Link', type: 'text', placeholder: '/about-us', group: 'Heading' },
      fontFamily: {
        label: 'Font',
        type: 'fontFamily',
        inlineNumber: { key: 'fontSize', placeholder: '32', suffix: 'px', width: 64 },
        group: 'Heading',
      },
      fontSize: { label: 'Size (px or em)', type: 'text', placeholder: '32px', group: 'Heading' },
      fontWeight: { label: 'Weight', type: 'fontWeight', group: 'Heading' },
      fontStyle: {
        label: 'Style',
        type: 'segmented',
        options: [
          { value: 'normal', label: '', icon: 'StyleNormal', title: 'Regular' },
          { value: 'italic', label: '', icon: 'StyleItalic', title: 'Italic' },
        ],
        group: 'Heading',
      },
      textDecoration: {
        label: 'Decoration',
        type: 'segmented',
        options: [
          { value: 'none', label: '', icon: 'DecorNone', title: 'None' },
          { value: 'underline', label: '', icon: 'DecorUnderline', title: 'Underline' },
          { value: 'line-through', label: '', icon: 'DecorLineThrough', title: 'Strikethrough' },
          { value: 'overline', label: '', icon: 'DecorOverline', title: 'Overline' },
        ],
        group: 'Heading',
      },
      textTransform: {
        label: 'Case',
        type: 'segmented',
        options: [
          { value: 'none', label: '', icon: 'CaseMixed', title: 'As typed' },
          { value: 'uppercase', label: '', icon: 'CaseUpper', title: 'UPPERCASE' },
          { value: 'lowercase', label: '', icon: 'CaseLower', title: 'lowercase' },
          { value: 'capitalize', label: '', icon: 'CaseCap', title: 'Capitalize Words' },
        ],
        group: 'Heading',
      },
      letterSpacing: { label: 'Letter spacing', type: 'letterSpacing', group: 'Heading' },
      color: { label: 'Text color', type: 'color', group: 'Heading' },
      textAlign: {
        label: 'Alignment',
        type: 'segmented',
        options: [
          { value: 'left', label: '', icon: 'AlignLeft' },
          { value: 'center', label: '', icon: 'AlignCenter' },
          { value: 'right', label: '', icon: 'AlignRight' },
        ],
        group: 'Heading',
      },
    },
};
