export default {
    label: 'Text',
    category: 'content',
    icon: 'T',
    acceptsChildren: false,
    allowedIn: ['page', 'Grid'],
    defaultProps: {
      text: 'Text block',
      href: '',
      color: '',
      fontSize: 14,
      lineHeight: 1.6,
      textAlign: 'left',
      fontWeight: 400,
      fontStyle: 'normal',
      textDecoration: 'none',
      textTransform: 'none',
      fontFamily: 'inherit',
      letterSpacing: 'normal',
    },
    propsSchema: {
      href: { label: 'Link (leave empty if not needed)', type: 'text', group: 'Text' },
      fontFamily: {
        label: 'Font',
        type: 'fontFamily',
        inlineNumber: { key: 'fontSize', placeholder: '14', suffix: 'px', width: 64 },
        group: 'Text',
      },
      fontSize: { label: 'Font size (px)', type: 'number', placeholder: '14', group: 'Text' },
      lineHeight: { label: 'Line height (×)', type: 'number', placeholder: '1.6', group: 'Text' },
      fontWeight: { label: 'Weight', type: 'fontWeight', group: 'Text' },
      fontStyle: {
        label: 'Style',
        type: 'segmented',
        options: [
          { value: 'normal', label: '', icon: 'StyleNormal', title: 'Regular' },
          { value: 'italic', label: '', icon: 'StyleItalic', title: 'Italic' },
        ],
        group: 'Text',
      },
      textDecoration: {
        label: 'Decoration',
        type: 'segmented',
        options: [
          { value: 'none', label: '', icon: 'DecorNone', title: 'None' },
          { value: 'underline', label: '', icon: 'DecorUnderline', title: 'Underline' },
          { value: 'line-through', label: '', icon: 'DecorLineThrough', title: 'Strikethrough' },
          { value: 'overline', label: '', icon: 'DecorOverline', title: 'Overline' },
        ],
        group: 'Text',
      },
      textTransform: {
        label: 'Case',
        type: 'segmented',
        options: [
          { value: 'none', label: '', icon: 'CaseMixed', title: 'As typed' },
          { value: 'uppercase', label: '', icon: 'CaseUpper', title: 'UPPERCASE' },
          { value: 'lowercase', label: '', icon: 'CaseLower', title: 'lowercase' },
          { value: 'capitalize', label: '', icon: 'CaseCap', title: 'Capitalize Words' },
        ],
        group: 'Text',
      },
      letterSpacing: { label: 'Letter spacing', type: 'letterSpacing', group: 'Text' },
      color: { label: 'Text color', type: 'color', group: 'Text' },
      textAlign: {
        label: 'Alignment',
        type: 'segmented',
        options: [
          { value: 'left', label: '', icon: 'AlignLeft' },
          { value: 'center', label: '', icon: 'AlignCenter' },
          { value: 'right', label: '', icon: 'AlignRight' },
          { value: 'justify', label: '', icon: 'AlignJustify' },
        ],
        group: 'Text',
      },
    },
};
